---
#-------------------------------
# General Site Settings
title: R Fox Data
email: ryanfox212@gmail.com
description: A personal data blog for Ryan Fox. # this appears in Google
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rfoxdata.co.uk" # the base hostname & protocol for your site
blog-theme: light

#-------------------------------
# Social Settings
github_username: rjjfox
linkedin_username: rjjfox

#-------------------------------
# Author Settings
author:
  name: Ryan Fox
  image: "/assets/img/desertpic.jpeg"

#-------------------------------
# Hero Settings
hero:
  hero__title: Hi, I'm <span class="hero__name">Ryan Fox</span>.
  hero__job: Data Scientist
  hero__description: I spend a lot of time with numbers
  hero__button__text: Read about my past
  hero__button__link: "/about"
  hero__image: "/assets/img/desertpic.jpeg"

#-------------------------------
# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
plugins:
  - jekyll-paginate

paginate: 9
paginate_path: "/page/:num"

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname: rfoxdata-co-uk

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# To enable projects as a new format of posts pages
collections:
  projects:
    output: true
