# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R Fox Data
email: ryanfox212@gmail.com
description: A personal data blog for Ryan Fox. # this appears in Google
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rfoxdata.co.uk" # the base hostname & protocol for your site
github_username: rjjfox

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: rfoxdata-co-uk

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# To enable projects as a new format of posts pages
collections:
  projects:
    output: true
  